name: git-gateway
branch: master
media_folder: "images"

collections:
  name: "index" # Collection for managing the content of the index page
  label: "Index Page" # Label for the collection
  file: "index.html" # Path to the index.html file
  label: "Index Page" # Label for the file
  fields: # Define fields for the index page
    - { label: "Title", name: "title", widget: "string" } # Title field
    - { label: "Description", name: "description", widget: "text" } # Description field
            # Add more fields as needed for managing content
