backend:
    name: git-gateway # Replace 'github' with your preferred backend provider
    branch: master # Branch to update (optional; defaults to master)

media_folder: "images"
public_folder: "/images"

collections:
    - name: "homepage_content"
      label: "Homepage Content"
      folder: "content/homepage"
      create: true
      extension: "md" # Specify the file extension
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
